insert into menu_t (name, pid, url) values ('活动管理', 0, '/activity/index');
insert into menu_t (name, pid, url) values ('专辑歌曲管理', 0, '/album/index');
insert into menu_t (name, pid, url) values ('专辑管理', 2, '/album/index');
insert into menu_t (name, pid, url) values ('歌曲管理', 2, '/music/index');
insert into menu_t (name, pid, url) values ('live show管理', 0, '/music/index');
insert into menu_t (name, pid, url) values ('日记管理', 0, '/diary/index');
insert into menu_t (name, pid, url) values ('乐队信息', 0, '/bandmember/index');
insert into menu_t (name, pid, url) values ('乐队介绍', 0, '/bandmember/index');
insert into menu_t (name, pid, url) values ('乐队成员', 0, '/bandmember/index');
insert into menu_t (name, pid, url) values ('乐队经历', 0, '/experience/index');
insert into menu_t (name, pid, url) values ('推广广告', 0, '/extend/index');
insert into menu_t (name, pid, url) values ('统计分析', 0, '');